apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: kafka-kafka-bootstrap:9092
  - name: consumerGroup
    value: profile-service
  - name: authType
    value: none
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: user-registered-sub
spec:
  pubsubname: pubsub
  topic: user-registered
  routes:
    default: /events/user-registered
scopes:
  - profile-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-solved-sub
spec:
  pubsubname: pubsub
  topic: task-solved
  routes:
    default: /events/task-solved
scopes:
  - profile-service
