apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-profile

build:
  local:
    push: false
    tryImportMissing: false
  insecureRegistries:
    - ${REGISTRY}
  artifacts:
    - image: profile-api
      custom:
        buildCommand: buildah --storage-driver=vfs bud --tag $IMAGE . && buildah --storage-driver=vfs push --tls-verify=false $IMAGE
        dependencies:
          paths:
            - "**/*.go"
            - go.mod
            - go.sum
            - Dockerfile
            - migrations/

deploy:
  helm:
    releases:
      - name: mathtrail-profile
        chartPath: infra/helm/mathtrail-profile
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true
        valuesFiles:
          - infra/helm/mathtrail-profile/values.yaml
          - infra/helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_mathtrail_profile}}"
          image.tag: "{{.IMAGE_TAG_mathtrail_profile}}"

portForward:
  - resourceType: service
    resourceName: mathtrail-profile
    namespace: mathtrail
    port: 8080
    localPort: 8081

requires:
  - configs:
      - profile-local-deps

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: profile-local-deps

build:
  artifacts: []

deploy:
  statusCheck: true
  helm:
    releases:
      - name: profile-postgres
        namespace: "{{.NAMESPACE}}"
        chartPath: infra/local/helm/profile-postgres
        createNamespace: true
        wait: true
        skipBuildDependencies: true

      - name: profile-pgbouncer
        namespace: "{{.NAMESPACE}}"
        chartPath: infra/local/helm/profile-pgbouncer
        createNamespace: true
        wait: true
        skipBuildDependencies: true

      - name: profile-redis
        namespace: "{{.NAMESPACE}}"
        chartPath: infra/local/helm/profile-redis
        createNamespace: true
        wait: true
        skipBuildDependencies: true
