apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mathtrail-profile

build:
  local:
    push: false
    tryImportMissing: false
  insecureRegistries:
    - k3d-mathtrail-registry.localhost:5050
  artifacts:
    - image: profile-api
      custom:
        buildCommand: buildah bud --tag $IMAGE . && buildah push --tls-verify=false $IMAGE
        dependencies:
          paths:
            - "**/*.go"
            - go.mod
            - go.sum
            - Dockerfile
            - migrations/

deploy:
  helm:
    releases:
      - name: mathtrail-profile
        chartPath: infra/helm/mathtrail-profile
        namespace: mathtrail
        createNamespace: true
        wait: true
        valuesFiles:
          - infra/helm/mathtrail-profile/values.yaml
          - infra/helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_mathtrail_profile}}"
          image.tag: "{{.IMAGE_TAG_mathtrail_profile}}"

portForward:
  - resourceType: service
    resourceName: mathtrail-profile
    namespace: mathtrail
    port: 8080
    localPort: 8081
