apiVersion: v2
name: profile-postgres
description: PostgreSQL for profile-api (local dev only)
version: 0.1.0
dependencies:
  - name: postgresql
    version: "18.5.5"
    repository: "https://MathTrail.github.io/charts/charts"
