apiVersion: v1
kind: Secret
metadata:
  name: profile-pgbouncer-userlist
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: profile-pgbouncer
    app.kubernetes.io/part-of: mathtrail
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  userlist.txt: |
    "pgbouncer_auth" "{{ .Values.auth.password }}"
