apiVersion: v2
name: mathtrail-profile
version: 0.1.0
description: MathTrail Profile Service chart
dependencies:
  - name: mathtrail-service-lib
    version: "0.1.4"
    repository: "https://MathTrail.github.io/charts/charts"
