apiVersion: v2
name: mathtrail-profile
version: 0.1.0
description: MathTrail Profile Service chart
dependencies:
  - name: base-chart
    version: 0.1.0
    repository: "file://../../../../mathtrail-infra/helm/base-chart"
