{{- if .Values.vaultConfig.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: {{ .Values.vaultConfig.db.connectionName }}
  namespace: vault-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  vaultAuthRef: vault-admin-auth
  path: database
  pluginName: postgresql-database-plugin
  connectionName: {{ .Values.vaultConfig.db.connectionName }}
  allowedRoles:
    - {{ .Values.vaultConfig.db.roleName }}
  connectionURL: "postgresql://{{`{{username}}`}}:{{`{{password}}`}}@postgres-postgresql.mathtrail.svc.cluster.local:5432/{{ .Values.vaultConfig.db.database }}?sslmode=disable"
  rootCredentials:
    username: postgres
    passwordSecret:
      name: postgres-postgresql
      namespace: mathtrail
      key: postgres-password
{{- end }}
